on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs: 
  deploy_test_coverage:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    container: 
      image: kcov/kcov:latest
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Install Act dependencies
        if: ${{ env.ACT }}
        shell: bash
        run: |
          apt-get update && apt-get install sudo git curl xz-utils ca-certificates -y ; \
          curl -Os https://cli.codecov.io/latest/linux/codecov ; \
          sudo chmod +x codecov ; \
          curl -Os https://ziglang.org/download/0.13.0/zig-linux-x86_64-0.13.0.tar.xz ; \
          tar xf ./zig-linux-x86_64-0.13.0.tar.xz ; \
      - name: Install xz-utils
        if: ${{ !env.ACT }}
        run: apt-get update && apt-get install xz-utils -y
      - name: Setup Zig Compiler
        uses: mlugg/setup-zig@v1.2.1
        if: ${{ !env.ACT }}          
        with:
          version: 0.13.0
      - name: Run tests & Generate Code Coverage
        run: ${{ env.ACT && './zig-linux-x86_64-0.13.0/zig' || 'zig' }} build cov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          binary: ${{ env.ACT && './codecov' || '' }}
          directory: ./kcov-output/test
          token: ${{ secrets.CODECOV_TOKEN }}
      
